[package]
name = "smbc"
version = "0.1.0"
authors = ["Konstantin Gribov <grossws@gmail.com>"]

repository = "https://github.com/smbc-rs/smbc"
documentation = "https://docs.rs/smbc"
license = "GPL-3.0+"
keywords = ["smbclient", "samba", "cifs"]
description = "type-safe libsmbclient wrapper with std::fs-like interface"
edition = "2018"

[dependencies]
libc = "~0.2"
log = "~0.4"
smbclient-sys = {git = "ssh://git@github.comcast.com/SDS/smbclient-sys.git"}
bitflags = "~1.0"
nix = "0.11"
chrono = "0.4.6"
nom = "4.1.1"
percent-encoding = "1.0.1"
lazy_static = "1.2.0"