[package]
name = "smbc"
version = "0.1.0"
authors = ["Konstantin Gribov <grossws@gmail.com>"]

repository = "https://github.com/smbc-rs/smbc"
documentation = "https://docs.rs/smbc"
license = "GPL-3.0+"
keywords = ["smbclient", "samba", "cifs"]
description = "type-safe libsmbclient wrapper with std::fs-like interface"

[dependencies]
libc = "~0.2"
log = "~0.4"
smbclient-sys = {path = "/home/mzhong215/smbclient-sys" }
bitflags = "~1.0"
<<<<<<< HEAD
nix = "0.11"
chrono = "0.4.6"
nom = "4.1.1"
=======
nix = "~0.11"
chrono = "~0.4"
>>>>>>> c0f14cc1c4a9fa68d9ce23e3e7330f39596d85e2
