indent_style = "Visual"
use_small_heuristics = "Max"
condense_wildcard_suffixes = true
imports_indent = "Visual"
merge_imports = true
reorder_impl_items = true
struct_lit_single_line = true
use_field_init_shorthand = true
use_try_shorthand = true
format_doc_comments = true
edition = "2018"
unstable_features = false